name = "bucketly"
compatibility_date = "2024-11-13"
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_SUPABASE_URL = ""
NEXT_PUBLIC_SUPABASE_ANON_KEY = ""

[env.production]
NODE_ENV = "production"

[env.preview]
NODE_ENV = "development"
